name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        host: [ windows-latest, ubuntu-latest ]
        include:
          - host: windows-latest
            cmake_config_settings: -T ClangCl
      fail-fast: false
    runs-on: ${{matrix.host}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release ${{matrix.cmake_config_settings}}

      - name: Build project
        run: cmake --build build --config Release -j
